# config.yaml
models:
  #- LLAVA-Video
  #- LLAVA-OneVision
  #- Mantis-FUYU
  #- Mantis-IDEFICS
  #- Pixtral
  #- Qwen2VL
  - Ovis3B
  - Molmo
  #- Ovis8B TODO not implemented

experiments:
  - exp1
  - exp2
  - exp3