# config.yaml
models:
  - LLAVA-Video
  - LLAVA-OneVision
  - Mantis-FUYU
  - Mantis-IDEFICS
  - Pixtral
  - Qwen2VL
  - Molmo
  - Ovis3B
  #- Ovis8B TODO not implemented

experiments:
  - exp1
  - exp2
  - exp3